-- ============================================================
-- SUPERSEDED (2026-06-12). DO NOT APPLY.
--
-- This patch carried retired offer claims:
--   - Signal described as a single-agent tier (Noell Support only).
--     Signal includes all three service agents.
--   - Retired B2B agent names (Noell Prospect, Noell Qualify,
--     Noell Nurture). Current agents are Noell Inbound, Noell
--     Pipeline, and Noell Account.
--   - Retired B2B tier names ("Prospect", "Enterprise"). Current
--     names are "Inbound" and "Full Stack".
--   - Retired "Revenue Signal Report" first step. The current first
--     step for service businesses is the free 30-minute Missed Call
--     Audit.
--   - The Digital Readiness Review described as free. It is $297,
--     fully credited toward any package.
--
-- The current support prompt lives in:
--   supabase/seeds/opsbynoell_prompt_pricing_truth_2026_06_12.sql
-- Apply that file instead. The original content of this patch is
-- preserved in git history.
-- ============================================================
